### ISSUE TITLE
Android playing local video

### ISSUE THREAD

**Issue by abbadabbatech** [rxlabz/flutter_video_launcher#5]
Can not seem to get videos to play locally on Android, the videos are in the application documents directory, have not seen an error, but its an mp4 and seems to not play, just black screen.

Any thoughts?  Does the path need to be in a particular format or something?

**Comment by ansgarkroger** [comment]
Same issue here. did you ever sort it?

**Comment by sridharmane** [comment]
Same issue here. Confirmed that the temp file is available. Funciton `canLaunchVideo` returns successfully. Exception occurs when calling the `launchVideo` function. Here is the stack trace:
```
E/flutter (13684): [ERROR:topaz/lib/tonic/logging/dart_error.cc(16)] Unhandled exception:
E/flutter (13684): type 'Future<dynamic>' is not a subtype of type 'Future<Null>' where
E/flutter (13684):   Future is from dart:async
E/flutter (13684):   Future is from dart:async
E/flutter (13684):   Null is from dart:core
E/flutter (13684): 
E/flutter (13684): #0      _SectionVideoState.build.<anonymous closure> (package:app/widgets/section_video.dart:132:23)
E/flutter (13684): <asynchronous suspension>
E/flutter (13684): #1      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:478:14)
E/flutter (13684): #2      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:530:30)
E/flutter (13684): #3      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
E/flutter (13684): #4      TapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:161:9)
E/flutter (13684): #5      TapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:123:7)
E/flutter (13684): #6      GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:156:27)
E/flutter (13684): #7      _WidgetsFlutterBinding&BindingBase&GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:147:20)
E/flutter (13684): #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:121:22)
E/flutter (13684): #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:101:7)
E/flutter (13684): #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:64:7)
E/flutter (13684): #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:48:7)
E/flutter (13684): #12     _invoke1 (dart:ui/hooks.dart:134:13)
E/flutter (13684): #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:5)
D/EGL_emulation(13684): eglMakeCurrent: 0x9de27860: ver 3 0 (tinfo 0x9d2ff170)
```

**Comment by juliocbcotta** [comment]
there is the related issue about, but it is not the cause of your issue.
You probably are trying to play a video in android 8 or 9.
This should fix the issue.
https://github.com/flutter/flutter/issues/37200#issuecomment-517095233
